### PR TITLE
allow explicit organization for CA; defaults to 'Cloud Foundry'

### PR DESCRIPTION
**Pull request by drnic**
_Old Note:_ I have not been able to test this with `bosh` CLI yet; see https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1533000031000127

**Update:** I've tested a cherry-picked version of this PR against tag `v0.0.124` (used by `bosh-cli`) which is at https://github.com/drnic/config-server/tree/x509-organization-0-0-124

### CODE REVIEW

**Comment by drnic** [comment]
I've also added support for a plural `organizations:` field, since certificates can be associated with multiple groups/organizations.

Demo from generating a CFCR cert:
```
        Subject: C=USA, O=system:nodes, O=drnic:nodes, CN=kubelet.cfcr.internal
```

**Comment by mfine30** [comment]
@freddesbiens @pivotal-jamil-shamy this is the issue that we discussed with Alex and the CFCR team today as well. Are you ok adding it to the Toronto backlog since it touches on config server?

**Comment by pivotal-jamil-shamy** [comment]
@mfine30 sorry for late reply, it should be in the backlog now https://www.pivotaltracker.com/story/show/159421491

**Comment by drnic** [comment]
Would you like a PR for `bosh` CLI now? Or will this get absorbed soon?

**Comment by freddesbiens** [comment]
Hi Nic,

We have been working on a story in the last few days. You can find the
latest here: https://www.pivotaltracker.com/story/show/159421491 Please let
me know if you have additional questions or concerns.

Best,

    Frédéric Desbiens
    Product Manager | Cloud Foundry BOSH

**Comment by pivotal-jamil-shamy** [comment]
Should be included in the next BOSH CLI release

**Pull request merged**
