### PR TITLE
Allow specify options for password

### PR DESCRIPTION
**Pull request by alex-slynko**

### CODE REVIEW

**Comment by cppforlife** [comment]
@alex-slynko is there a particular component that requires customizable letter range? this project is meant to be a reference implementation for config server API so im trying to keep it very bare. there is going to be a different project open sourced shortly that will have much more customizable behaviour cc @pivotal-danjahner

**Comment by alex-slynko** [comment]
@cppforlife I am more interested in `bosh-cli interpolate` generation. As I understood this code is reused in bosh-cli repo.
I would like to be able to generate little bit more from `bosh-cli`.

**Comment by cppforlife** [comment]
can you elaborate how would you use it in bosh cli? is it related to bosh-deployment? which component?

**Comment by alex-slynko** [comment]
@cppforlife I warted to generate secret HEX key for another implementation of config server
 I don't think that is required for generic config server.

**Pull request closed without merging**
